PRODUCT = {
    1: "Unleaded Petrol",
    2: "Premium Unleaded",
    4: "Diesel",
    5: "LPG",
    6: "98 RON",
    10: "E85",
    11: "Brand diesel",
}

REGION = {
    1: "Boulder",
    2: "Broome",
    3: "Busselton (Townsite)",
    4: "Carnarvon",
    5: "Collie",
    6: "Dampier",
    7: "Esperance",
    8: "Kalgoorlie",
    9: "Karratha",
    10: "Kununurra",
    11: "Narrogin",
    12: "Northam",
    13: "Port Hedland",
    14: "South Hedland",
    15: "Albany",
    16: "Bunbury",
    17: "Geraldton",
    18: "Mandurah",
    19: "Capel",
    20: "Dardanup",
    21: "Greenough",
    22: "Harvey",
    23: "Murray",
    24: "Waroona",
    25: "Metro : North of River",
    26: "Metro : South of River",
    27: "Metro : East/Hills",
    28: "Augusta / Margaret River",
    29: "Busselton (Shire)",
    30: "Bridgetown / Greenbushes",
    31: "Donnybrook / Balingup",
    32: "Manjimup",
    33: "Cataby",
    34: "Coolgardie",
    35: "Cunderdin",
    36: "Dalwallinu",
    37: "Denmark",
    38: "Derby",
    39: "Dongara",
    40: "Exmouth",
    41: "Fitzroy Crossing",
    42: "Jurien",
    43: "Kambalda",
    44: "Kellerberrin",
    45: "Kojonup",
    46: "Meekatharra",
    47: "Moora",
    48: "Mount Barker",
    49: "Newman",
    50: "Norseman",
    51: "Ravensthorpe",
    53: "Tammin",
    54: "Williams",
    55: "Wubin",
    56: "York",
    57: "Regans Ford",
    58: "Meckering",
    59: "Wundowie",
    60: "North Bannister",
    61: "Munglinup",
    62: "Northam (Shire)",
    63: "Bodallin",
}

BRAND = {
    2: "Ampol",
    3: "Better Choice",
    4: "BOC",
    5: "BP",
    6: "Caltex",
    7: "Gull",
    8: "Kleenheat",
    9: "Kwikfuel",
    10: "Liberty",
    11: "Mobil",
    13: "Peak",
    14: "Shell",
    15: "Independent",
    19: "Caltex Woolworths",
    20: "Coles Express",
    23: "United",
    24: "Eagle",
    25: "FastFuel 24/7",
    26: "Puma",
    27: "Vibe",
    29: "7-Eleven",
    30: "Metro Petroleum",
    31: "WA Fuels",
    32: "Costco",
    33: "Mogas",
    34: "Atlas",
    35: "EG Ampol",
    36: "CGL fuel",
    37: "X Convenience",
    38: "Phoenix",
    39: "Burk",
    40: "Petro Fuels",
    41: "Astron",
    42: "OTR",
    43: "Reddy Express",
    44: "Dunning's",
    45: "Perrys",
    46: "UGO",
    47: "Maisey Fuels",
}

SUBURB = [
    "Albany",
    "Alexander Heights",
    "Alkimos",
    "Alfred Cove",
    "Applecross",
    "Armadale",
    "Ascot",
    "Ashby",
    "Attadale",
    "Augusta",
    "Australind",
    "Aveley",
    "Balcatta",
    "Baldivis",
    "Balga",
    "Balingup",
    "Ballajura",
    "Banksia Grove",
    "Barragup",
    "Baskerville",
    "Bassendean",
    "Bayswater",
    "Beckenham",
    "Bedford",
    "Bedfordale",
    "Beechboro",
    "Beeliar",
    "Beldon",
    "Bellevue",
    "Belmont",
    "Benger",
    "Bentley",
    "Bertram",
    "Bibra Lake",
    "Bicton",
    "Binningup",
    "Booragoon",
    "Boulder",
    "Bouvard",
    "Boyanup",
    "Brabham",
    "Brentwood",
    "Bridgetown",
    "Broome",
    "Brunswick Junction",
    "Bull Creek",
    "Bullsbrook",
    "Bunbury",
    "Burswood",
    "Busselton",
    "Butler",
    "Byford",
    "Calista",
    "Camillo",
    "Canning Vale",
    "Cannington",
    "Carey Park",
    "Capel",
    "Carbunup River",
    "Carine",
    "Carlisle",
    "Carnarvon",
    "Cataby",
    "Casuarina",
    "Caversham",
    "Chidlow",
    "Claremont",
    "Clarkson",
    "Cloverdale",
    "Cockburn Central",
    "Collie",
    "Como",
    "Coolgardie",
    "Coolup",
    "Cottesloe",
    "Cowaramup",
    "Cunderdin",
    "Currambine",
    "Dalwallinu",
    "Dampier",
    "Dardanup",
    "Dawesville",
    "Dayton",
    "Denmark",
    "Derby",
    "Dianella",
    "Dongara",
    "Donnybrook",
    "Doubleview",
    "Duncraig",
    "Dunsborough",
    "Dwellingup",
    "East Bunbury",
    "East Fremantle",
    "East Perth",
    "East Rockingham",
    "East Victoria Park",
    "Eaton",
    "Edgewater",
    "Ellenbrook",
    "Embleton",
    "Erskine",
    "Esperance",
    "Exmouth",
    "Falcon",
    "Fitzroy Crossing",
    "Floreat",
    "Forrestdale",
    "Forrestfield",
    "Fremantle",
    "Gelorup",
    "Geraldton",
    "Gidgegannup",
    "Girrawheen",
    "Glen Forrest",
    "Glendalough",
    "Glenfield",
    "Glen Iris",
    "Gnangara",
    "Golden Bay",
    "Gosnells",
    "Gracetown",
    "Greenbushes",
    "Greenfields",
    "Greenough",
    "Greenwood",
    "Guildford",
    "Gwelup",
    "Halls Head",
    "Hamilton Hill",
    "Harrisdale",
    "Harvey",
    "Henderson",
    "Henley Brook",
    "Herne Hill",
    "High Wycombe",
    "Highgate",
    "Hillarys",
    "Huntingdale",
    "Innaloo",
    "Jandakot",
    "Jarrahdale",
    "Jindalee",
    "Jolimont",
    "Joondalup",
    "Jurien Bay",
    "Kalamunda",
    "Kalgoorlie",
    "Kambalda",
    "Karawara",
    "Kardinya",
    "Karragullen",
    "Karratha",
    "Karridale",
    "Karrinyup",
    "Karnup",
    "Kellerberrin",
    "Kelmscott",
    "Kewdale",
    "Kiara",
    "Kingsley",
    "Kirup",
    "Kojonup",
    "Koondoola",
    "Kununurra",
    "Kwinana",
    "Kwinana Beach",
    "Kwinana Town Centre",
    "Lakelands",
    "Landsdale",
    "Langford",
    "Leda",
    "Leederville",
    "Leeming",
    "Lesmurdie",
    "Lexia",
    "Lynwood",
    "Maddington",
    "Madeley",
    "Maida Vale",
    "Malaga",
    "Mandurah",
    "Manjimup",
    "Manning",
    "Manypeaks",
    "Margaret River",
    "Meadow Springs",
    "Meekatharra",
    "Merriwa",
    "Middle Swan",
    "Midland",
    "Midvale",
    "Mindarie",
    "Mirrabooka",
    "Moonyoonooka",
    "Moora",
    "Morley",
    "Mosman Park",
    "Mount Barker",
    "Mount Helena",
    "Mount Lawley",
    "Mount Pleasant",
    "Mt Hawthorn",
    "Mt Helena",
    "Mt Lawley",
    "Mt Pleasant",
    "Mullaloo",
    "Mundaring",
    "Mundijong",
    "Munster",
    "Murdoch",
    "Myalup",
    "Myaree",
    "Narrogin",
    "Naval Base",
    "Nedlands",
    "Neerabup",
    "Newman",
    "Nollamara",
    "Noranda",
    "Norseman",
    "North Dandalup",
    "North Fremantle",
    "North Perth",
    "Northam",
    "Northbridge",
    "Northcliffe",
    "Nowergup",
    "O'Conner",
    "Ocean Reef",
    "Oakford",
    "Osborne Park",
    "Padbury",
    "Palmyra",
    "Parmelia",
    "Pearsall",
    "Pemberton",
    "Perth",
    "Perth Airport",
    "Piara Waters",
    "Picton",
    "Pinjarra",
    "Port Hedland",
    "Port Kennedy",
    "Preston Beach",
    "Queens Park",
    "Quinns Rock",
    "Quinns Rocks",
    "Ravensthorpe",
    "Redcliffe",
    "Redmond",
    "Ridgewood",
    "Riverton",
    "Rivervale",
    "Rockingham",
    "Roleystone",
    "Rosa Brook",
    "Rottnest Island",
    "Safety Bay",
    "Sawyers Valley",
    "Scarborough",
    "Secret Harbour",
    "Serpentine",
    "Seville Grove",
    "Shoalwater",
    "Singleton",
    "Sorrento",
    "South Bunbury",
    "South Fremantle",
    "South Hedland",
    "South Lake",
    "South Perth",
    "South Yunderup",
    "Southern River",
    "Spearwood",
    "Stratham Downs",
    "Stratton",
    "Subiaco",
    "Success",
    "Swan View",
    "Swanbourne",
    "Tammin",
    "The Lakes",
    "Thornlie",
    "Tuart Hill",
    "Upper Swan",
    "Vasse",
    "Victoria Park",
    "Vittoria",
    "Waikiki",
    "Walpole",
    "Wangara",
    "Wanneroo",
    "Warnbro",
    "Waroona",
    "Warwick",
    "Waterloo",
    "Wattle Grove",
    "Wedgefield",
    "Wellstead",
    "Welshpool",
    "Wembley",
    "West Perth",
    "West Swan",
    "Westfield",
    "Westminster",
    "Willetton",
    "Williams",
    "Withers",
    "Witchcliffe",
    "Woodbridge",
    "Woodvale",
    "Wooroloo",
    "Wubin",
    "Yanchep",
    "Yangebup",
    "Yokine",
    "York",
    "Young Siding",
    "Yunderup",
]
